FROM openjdk:11-jdk-slim as build
RUN curl -sL https://deb.nodesource.com/setup_14.x | bash -
RUN apt-get update -qq && apt-get install -qq --no-install-recommends nodejs

# Stop running as root at this point
RUN useradd -m myuser
WORKDIR /usr/src/app/
RUN chown myuser:myuser /usr/src/app/
USER myuser

# Copy pom.xml and prefetch dependencies so a repeated build can continue from the next step with existing dependencies
COPY --chown=myuser *.gradle ./

# Copy all needed project files to a folder
COPY --chown=myuser:myuser src src
COPY --chown=myuser:myuser frontend frontend
COPY --chown=myuser:myuser .npmrc ./
COPY --chown=myuser:myuser package.json ./
COPY --chown=myuser:myuser tsconfig.json ./
COPY --chown=myuser:myuser types.d.ts ./

# Using * after the files that are autogenerated so that so build won't fail if they are not yet created
COPY --chown=myuser:myuser package-lock.json* pnpm-lock.yaml* webpack.config.js* ./

COPY --chown=myuser:myuser gradle ./
COPY --chown=myuser:myuser gradlew ./

RUN chmod +x gradlew

RUN ./gradlew installDist
RUN rm build/install/*/bin/*.bat

# Running stage: the part that is used for running the application
FROM openjdk:11-jdk-slim
COPY --from=build /usr/src/app/build/install/* /usr/app
RUN useradd -m myuser
USER myuser
EXPOSE 8080
CMD ./usr/app/bin/*
